import { Faction } from "./faction";
import { Force } from "./force";
import { StormPosition } from "./storm";

export type Space = {
    name: string;
    type: 'sand' | 'sink' | 'rock' | 'stronghold' | 'shielded-stronghold' | 'shielded-sand';
    spiceBlow: number | null;
    spiceBlowSector: number | null;
    sectors: StormPosition[];
}

export const SpaceList:Space[] = [
    {name: 'Arsunt', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [10, 11]},
    {name: 'Basin', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [8,]},
    {name: 'Bight-of-the-Cliff', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [13, 14]},
    {name: 'Broken-Land', type: 'sand', spiceBlow: 11, spiceBlowSector: 8, sectors: [10, 11]},
    {name: 'Cielago-Depression', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [0, 1, 2]},
    {name: 'Cielago-East', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [2, 3]},
    {name: 'Cielago-North', type: 'sand', spiceBlow: 2, spiceBlowSector: 8, sectors: [0, 1, 2]},
    {name: 'Cielago-South', type: 'sand', spiceBlow: 1, spiceBlowSector: 12, sectors: [1, 2]},
    {name: 'Cielago-West', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [0, 17]},
    {name: 'Funeral-Plain', type: 'sand', spiceBlow: 14, spiceBlowSector: 6, sectors: [14,]},
    {name: 'Gara-Kulon', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [7,]},
    {name: 'Habbanya-Erg', type: 'sand', spiceBlow: 15, spiceBlowSector: 8, sectors: [15, 16]},
    {name: 'Habbanya-Ridge-Flat', type: 'sand', spiceBlow: 17, spiceBlowSector: 10, sectors: [16, 17]},
    {name: 'Hagga-Basin', type: 'sand', spiceBlow: 12, spiceBlowSector: 6, sectors: [11, 12]},
    {name: 'Harg-Pass', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [3, 4]},
    {name: 'Hole-in-the-Rock', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [8,]},
    {name: 'Meridian', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [0, 1]},
    {name: 'Old-Gap', type: 'sand', spiceBlow: 9, spiceBlowSector: 6, sectors: [8, 9, 10]},
    {name: 'Red-Chasm', type: 'sand', spiceBlow: 6, spiceBlowSector: 8, sectors: [6,]},
    {name: 'Rock-Outcroppings', type: 'sand', spiceBlow: 13, spiceBlowSector: 6, sectors: [12, 13]},
    {name: 'Sihaya-Ridge', type: 'sand', spiceBlow: 8, spiceBlowSector: 6, sectors: [8,]},
    {name: 'South-Mesa', type: 'sand', spiceBlow: 4, spiceBlowSector: 10, sectors: [3, 4, 5]},
    {name: 'The-Great-Flat', type: 'sand', spiceBlow: 14, spiceBlowSector: 10, sectors: [14,]},
    {name: 'The-Greater-Flat', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [15,]},
    {name: 'Minor-Erg', type: 'sand', spiceBlow: 7, spiceBlowSector: 8, sectors: [4, 5, 6, 7]},
    {name: 'Tsimpo', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [10, 11, 12]},
    {name: 'Wind-Pass', type: 'sand', spiceBlow: null, spiceBlowSector: null, sectors: [13, 14, 15, 16]},
    {name: 'Wind-Pass-North', type: 'sand', spiceBlow: 16, spiceBlowSector: 6, sectors: [16, 17]},
    {name: 'Polar-Sink', type: 'sink', spiceBlow: null, spiceBlowSector: null, sectors: []},
    {name: 'False-Wall-East', type: 'rock', spiceBlow: null, spiceBlowSector: null, sectors: [4, 5, 6, 7, 8]},
    {name: 'False-Wall-South', type: 'rock', spiceBlow: null, spiceBlowSector: null, sectors: [3, 4]},
    {name: 'False-Wall-West', type: 'rock', spiceBlow: null, spiceBlowSector: null, sectors: [15, 16, 17]},
    {name: 'Pasty-Mesa', type: 'rock', spiceBlow: null, spiceBlowSector: null, sectors: [4, 5, 6, 7]},
    {name: 'Plastic-Basin', type: 'rock', spiceBlow: null, spiceBlowSector: null, sectors: [11, 12, 13]},
    {name: 'Rim-Wall-West', type: 'rock', spiceBlow: null, spiceBlowSector: null, sectors: [8,]},
    {name: 'Shield-Wall', type: 'rock', spiceBlow: null, spiceBlowSector: null, sectors: [7, 8]},
    {name: 'Habbanya-Sietch', type: 'stronghold', spiceBlow: null, spiceBlowSector: null, sectors: [16,]},
    {name: 'Sietch-Tabr', type: 'stronghold', spiceBlow: null, spiceBlowSector: null, sectors: [13,]},
    {name: 'Tueks-Sietch', type: 'stronghold', spiceBlow: null, spiceBlowSector: null, sectors: [4,]},
    {name: 'Arrakeen', type: 'shielded-stronghold', spiceBlow: null, spiceBlowSector: null, sectors: [9,]},
    {name: 'Carthag', type: 'shielded-stronghold', spiceBlow: null, spiceBlowSector: null, sectors: [10,]},
    {name: 'Imperial-Basin', type: 'shielded-sand', spiceBlow: null, spiceBlowSector: null, sectors: [8, 9, 10]}
] 


export const SpaceAdjacencyList:[{name:string, sector:number}, {name:string, sector:number}][] = [
    [{name:'Arsunt', sector: 10}, {name:'Carthag', sector: 10}],
    [{name:'Arsunt', sector: 10}, {name:'Imperial-Basin', sector: 10}],
    [{name:'Arsunt', sector: 10}, {name:'Polar-Sink', sector: -1}],
    [{name:'Arsunt', sector: 10}, {name:'Hagga Basin', sector: 11}],
    [{name:'Arsunt', sector: 11}, {name:'Polar-Sink', sector: -1}],
    [{name:'Arsunt', sector: 11}, {name:'Hagga Basin', sector: 11}],
    [{name:'Arsunt', sector: 11}, {name:'Hagga Basin', sector: 12}],
    [{name:'Basin', sector: 8}, {name:'Old-Gap', sector: 8}],
    [{name:'Basin', sector: 8}, {name:'Rim-Wall-West', sector: 8}],
    [{name:'Basin', sector: 8}, {name:'Hole-in-the-Rock', sector: 8}],
    [{name:'Basin', sector: 8}, {name:'Sihaya-Ridge', sector: 8}],
    [{name:'Bight-of-the-Cliff', sector: 13}, {name:'Rock-Outcroppings', sector: 13}],
    [{name:'Bight-of-the-Cliff', sector: 13}, {name:'Sietch-Tabr', sector: 13}],
    [{name:'Bight-of-the-Cliff', sector: 13}, {name:'Plastic-Basin', sector: 13}],
    [{name:'Bight-of-the-Cliff', sector: 14}, {name:'Funeral-Plain', sector: 14}],
    [{name:'Broken-Land', sector: 10}, {name:'Old-Gap', sector: 10}],
    [{name:'Broken-Land', sector: 10}, {name:'Tsimpo', sector: 10}],
    [{name:'Broken-Land', sector: 11}, {name:'Tsimpo', sector: 11}],
    [{name:'Broken-Land', sector: 11}, {name:'Rock-Outcroppings', sector: 12}],
    [{name:'Broken-Land', sector: 11}, {name:'Plastic-Basin', sector: 11}],
    [{name:'Cielago-Depression', sector: 0}, {name:'Cielago-North', sector: 0}],
    [{name:'Cielago-Depression', sector: 0}, {name:'Meridian', sector: 0}],
    [{name:'Cielago-Depression', sector: 0}, {name:'Cielago-West', sector: 0}],
    [{name:'Cielago-Depression', sector: 1}, {name:'Cielago-North', sector: 1}],
    [{name:'Cielago-Depression', sector: 1}, {name:'Meridian', sector: 1}],
    [{name:'Cielago-Depression', sector: 1}, {name:'Cielago-South', sector: 1}],
    [{name:'Cielago-Depression', sector: 2}, {name:'Cielago-North', sector: 2}],
    [{name:'Cielago-Depression', sector: 2}, {name:'Cielago-South', sector: 2}],
    [{name:'Cielago-Depression', sector: 2}, {name:'Cielago-East', sector: 2}],
    [{name:'Cielago-East', sector: 2}, {name:'Cielago-South', sector: 2}],
    [{name:'Cielago-East', sector: 2}, {name:'Cielago-North', sector: 2}],
    [{name:'Cielago-East', sector: 3}, {name:'South-Mesa', sector: 3}],
    [{name:'Cielago-East', sector: 3}, {name:'False-Wall-South', sector: 3}],
    [{name:'Cielago-North', sector: 0}, {name:'Wind-Pass-North', sector: 17}],
    [{name:'Cielago-North', sector: 0}, {name:'Cielago-West', sector: 17}],
    [{name:'Cielago-North', sector: 0}, {name:'Cielago-West', sector: 0}],
    [{name:'Cielago-North', sector: 0}, {name:'Polar-Sink', sector: -1}],
    [{name:'Cielago-North', sector: 1}, {name:'Polar-Sink', sector: -1}],
    [{name:'Cielago-North', sector: 2}, {name:'Polar-Sink', sector: -1}],
    [{name:'Cielago-North', sector: 2}, {name:'Harg-Pass', sector: 3}],
    [{name:'Cielago-North', sector: 2}, {name:'False-Wall-South', sector: 3}],
    [{name:'Cielago-South', sector: 1}, {name:'Meridian', sector: 1}],
    [{name:'Cielago-West', sector: 17}, {name:'Wind-Pass', sector: 16}],
    [{name:'Cielago-West', sector: 17}, {name:'Wind-Pass-North', sector: 17}],
    [{name:'Cielago-West', sector: 17}, {name:'False-Wall-West', sector: 17}],
    [{name:'Cielago-West', sector: 17}, {name:'Habbanya-Ridge-Flat', sector: 17}],
    [{name:'Cielago-West', sector: 0}, {name:'Meridian', sector: 0}],
    [{name:'Funeral-Plain', sector: 14}, {name:'Plastic-Basin', sector: 13}],
    [{name:'Funeral-Plain', sector: 14}, {name:'The-Great-Flat', sector: 14}],
    [{name:'Gara-Kulon', sector: 7}, {name:'Sihaya-Ridge', sector: 8}],
    [{name:'Gara-Kulon', sector: 7}, {name:'Shield-Wall', sector: 7}],
    [{name:'Gara-Kulon', sector: 7}, {name:'Pasty-Mesa', sector: 7}],
    [{name:'Habbanya-Erg', sector: 15}, {name:'The-Greater-Flat', sector: 15}],
    [{name:'Habbanya-Erg', sector: 15}, {name:'Habbanya-Ridge-Flat', sector: 16}],
    [{name:'Habbanya-Erg', sector: 16}, {name:'Habbanya-Ridge-Flat', sector: 16}],
    [{name:'Habbanya-Erg', sector: 16}, {name:'False-Wall-West', sector: 16}],
    [{name:'Habbanya-Ridge-Flat', sector: 16}, {name:'False-Wall-West', sector: 16}],
    [{name:'Habbanya-Ridge-Flat', sector: 16}, {name:'Habbanya-Sietch', sector: 16}],
    [{name:'Habbanya-Ridge-Flat', sector: 17}, {name:'Habbanya-Sietch', sector: 16}],
    [{name:'Habbanya-Ridge-Flat', sector: 17}, {name:'False-Wall-West', sector: 17}],
    [{name:'Habbanya-Ridge-Flat', sector: 17}, {name:'Meridian', sector: 0}],
    [{name:'Hagga-Basin', sector: 11}, {name:'Carthag', sector: 10}],
    [{name:'Hagga-Basin', sector: 11}, {name:'Tsimpo', sector: 11}],
    [{name:'Hagga-Basin', sector: 12}, {name:'Polar-Sink', sector: -1}],
    [{name:'Hagga-Basin', sector: 12}, {name:'Tsimpo', sector: 12}],
    [{name:'Hagga-Basin', sector: 12}, {name:'Plastic-Basin', sector: 12}],
    [{name:'Hagga-Basin', sector: 12}, {name:'Plastic-Basin', sector: 13}],
    [{name:'Hagga-Basin', sector: 12}, {name:'Wind-Pass', sector: 13}],
    [{name:'Harg-Pass', sector: 3}, {name:'Polar-Sink', sector: -1}],
    [{name:'Harg-Pass', sector: 3}, {name:'False-Wall-East', sector: 4}],
    [{name:'Harg-Pass', sector: 3}, {name:'False-Wall-South', sector: 3}],
    [{name:'Harg-Pass', sector: 4}, {name:'False-Wall-East', sector: 4}],
    [{name:'Harg-Pass', sector: 4}, {name:'False-Wall-South', sector: 4}],
    [{name:'Harg-Pass', sector: 4}, {name:'Minor-Erg', sector: 4}],
    [{name:'Hole-in-the-Rock', sector: 8}, {name:'Rim-Wall-West', sector: 8}],
    [{name:'Hole-in-the-Rock', sector: 8}, {name:'Imperial-Basin', sector: 8}],
    [{name:'Hole-in-the-Rock', sector: 8}, {name:'Shield-Wall', sector: 8}],
    [{name:'Hole-in-the-Rock', sector: 8}, {name:'Sihaya-Ridge', sector: 8}],
    [{name:'Old-Gap', sector: 8}, {name:'Rim-Wall-West', sector: 8}],
    [{name:'Old-Gap', sector: 9}, {name:'Arrakeen', sector: 9}],
    [{name:'Old-Gap', sector: 9}, {name:'Imperial-Basin', sector: 9}],
    [{name:'Old-Gap', sector: 10}, {name:'Tsimpo', sector: 10}],
    [{name:'Red-Chasm', sector: 6}, {name:'South-Mesa', sector: 5}],
    [{name:'Red-Chasm', sector: 6}, {name:'Pasty-Mesa', sector: 6}],
    [{name:'Rock-Outcroppings', sector: 12}, {name:'Plastic-Basin', sector: 12}],
    [{name:'Rock-Outcroppings', sector: 13}, {name:'Sietch-Tabr', sector: 13}],
    [{name:'Rock-Outcroppings', sector: 13}, {name:'Plastic-Basin', sector: 13}],
    [{name:'Sihaya-Ridge', sector: 8}, {name:'Shield-Wall', sector: 8}],
    [{name:'South-Mesa', sector: 3}, {name:'False-Wall-South', sector: 3}],
    [{name:'South-Mesa', sector: 4}, {name:'False-Wall-South', sector: 4}],
    [{name:'South-Mesa', sector: 4}, {name:'Tueks-Sietch', sector: 4}],
    [{name:'South-Mesa', sector: 4}, {name:'Pasty-Mesa', sector: 4}],
    [{name:'South-Mesa', sector: 5}, {name:'Pasty-Mesa', sector: 5}],
    [{name:'The-Great-Flat', sector: 14}, {name:'The-Greater-Flat', sector: 15}],
    [{name:'The-Great-Flat', sector: 14}, {name:'Wind-Pass', sector: 14}],
    [{name:'The-Great-Flat', sector: 14}, {name:'Plastic-Basin', sector: 13}],
    [{name:'The-Greater-Flat', sector: 15}, {name:'Wind-Pass', sector: 15}],
    [{name:'The-Greater-Flat', sector: 15}, {name:'False-Wall-West', sector: 15}],
    [{name:'Minor-Erg', sector: 4}, {name:'False-Wall-East', sector: 4}],
    [{name:'Minor-Erg', sector: 4}, {name:'False-Wall-South', sector: 4}],
    [{name:'Minor-Erg', sector: 4}, {name:'Pasty-Mesa', sector: 4}],
    [{name:'Minor-Erg', sector: 5}, {name:'False-Wall-East', sector: 5}],
    [{name:'Minor-Erg', sector: 5}, {name:'Pasty-Mesa', sector: 5}],
    [{name:'Minor-Erg', sector: 6}, {name:'Pasty-Mesa', sector: 6}],
    [{name:'Minor-Erg', sector: 6}, {name:'False-Wall-East', sector: 6}],
    [{name:'Minor-Erg', sector: 7}, {name:'False-Wall-East', sector: 7}],
    [{name:'Minor-Erg', sector: 7}, {name:'Pasty-Mesa', sector: 7}],
    [{name:'Minor-Erg', sector: 7}, {name:'Shield-Wall', sector: 7}],
    [{name:'Tsimpo', sector: 10}, {name:'Carthag', sector: 10}],
    [{name:'Tsimpo', sector: 10}, {name:'Imperial-Basin', sector: 10}],
    [{name:'Tsimpo', sector: 11}, {name:'Carthag', sector: 10}],
    [{name:'Tsimpo', sector: 11}, {name:'Plastic-Basin', sector: 11}],
    [{name:'Tsimpo', sector: 12}, {name:'Plastic-Basin', sector: 12}],
    [{name:'Wind-Pass', sector: 13}, {name:'Plastic-Basin', sector: 13}],
    [{name:'Wind-Pass', sector: 13}, {name:'Polar-Sink', sector: -1}],
    [{name:'Wind-Pass', sector: 14}, {name:'Polar-Sink', sector: -1}],
    [{name:'Wind-Pass', sector: 15}, {name:'Polar-Sink', sector: -1}],
    [{name:'Wind-Pass', sector: 15}, {name:'Wind-Pass-North', sector: 16}],
    [{name:'Wind-Pass', sector: 15}, {name:'False-Wall-West', sector: 15}],
    [{name:'Wind-Pass', sector: 16}, {name:'Wind-Pass-North', sector: 16}],
    [{name:'Wind-Pass', sector: 16}, {name:'False-Wall-West', sector: 16}],
    [{name:'Wind-Pass-North', sector: 16}, {name:'Polar-Sink', sector: -1}],
    [{name:'Wind-Pass-North', sector: 17}, {name:'Polar-Sink', sector: -1}],
    [{name:'Polar-Sink', sector: -1}, {name:'False-Wall-East', sector: 4}],
    [{name:'Polar-Sink', sector: -1}, {name:'False-Wall-East', sector: 5}],
    [{name:'Polar-Sink', sector: -1}, {name:'False-Wall-East', sector: 6}],
    [{name:'Polar-Sink', sector: -1}, {name:'False-Wall-East', sector: 7}],
    [{name:'Polar-Sink', sector: -1}, {name:'Imperial-Basin', sector: 8}],
    [{name:'Polar-Sink', sector: -1}, {name:'Imperial-Basin', sector: 9}],
    [{name:'False-Wall-East', sector: 7}, {name:'Shield-Wall', sector: 7}],
    [{name:'False-Wall-East', sector: 8}, {name:'Shield-Wall', sector: 8}],
    [{name:'False-Wall-East', sector: 8}, {name:'Imperial-Basin', sector: 8}],
    [{name:'False-Wall-South', sector: 3}, {name:'Tueks-Sietch', sector: 4}],
    [{name:'False-Wall-South', sector: 4}, {name:'Tueks-Sietch', sector: 4}],
    [{name:'False-Wall-South', sector: 4}, {name:'Pasty-Mesa', sector: 4}],
    [{name:'Pasty-Mesa', sector: 4}, {name:'Tueks-Sietch', sector: 4}],
    [{name:'Pasty-Mesa', sector: 5}, {name:'Tueks-Sietch', sector: 4}],
    [{name:'Pasty-Mesa', sector: 7}, {name:'Shield-Wall', sector: 7}],
    [{name:'Plastic-Basin', sector: 13}, {name:'Sietch-Tabr', sector: 13}],
    [{name:'Rim-Wall-West', sector: 8}, {name:'Arrakeen', sector: 9}],
    [{name:'Rim-Wall-West', sector: 8}, {name:'Imperial-Basin', sector: 8}],
    [{name:'Rim-Wall-West', sector: 8}, {name:'Imperial-Basin', sector: 9}],
    [{name:'Arrakeen', sector: 9}, {name:'Imperial-Basin', sector: 9}],
    [{name:'Carthag', sector: 10}, {name:'Imperial-Basin', sector: 10}],
]

export type SpaceState = {
    space:Space;
    spice:number;
    forces:Map<Faction,Map<StormPosition, Force>>
};
